# Generated by Django 6.0.1 on 2026-02-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("STUDENT", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BorrowRecord",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
