# Generated by Django 6.0.1 on 2026-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("STUDENT", "0002_delete_borrowrecord_delete_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("joined_date", models.DateField()),
            ],
        ),
    ]
